### PR TITLE
nc command line change for ubuntu compatibility

### PR DESCRIPTION
**Pull request by blaufish**
https://github.com/latchset/clevis/issues/50

nc command line bork'ed on ubuntu and other BSD nc based system.

pull request tested on Ubuntu only.

### CODE REVIEW

**Comment by blaufish** [comment]
An alternative to my PR from Ubuntu official patches.
Unclear to me which dependency solution is best.
```
cat debian/src/clevis-8/debian/patches/use-socat.patch
Description: Use socat in clevis-luks-askpass
Author: Christoph Biedl <debian.axhn@manchmal.in-ulm.de>
Date: 2017-11-28
Forwarded: not-needed
   
    Upstream assumes the nc program is ncat as provided by nmap. Since
    nmap is a fairly huge package and does not ship a separate ncat
    package (#881639), use socat instead for the time being.

    Thanks Anthony R Fletcher <arif@mail.nih.gov> for figuring out
    and testing.

--- a/src/dracut/module-setup.sh.in
+++ b/src/dracut/module-setup.sh.in
@@ -43,7 +43,7 @@
         clevis \
         curl \
         jose \
-        nc
+        socat
 
     dracut_need_initqueue
 }
--- a/src/systemd/clevis-luks-askpass
+++ b/src/systemd/clevis-luks-askpass
@@ -41,7 +41,7 @@
         [ "$uuid" != "$UUID" ] && continue
 
         if pt="`luksmeta load -d $d -s $slot -u $UUID | clevis decrypt`"; then
-            echo -n "+$pt" | nc -U -u --send-only "$s"
+            echo -n "+$pt" | socat -U "UNIX:$s" -
             break
         fi
     done
```

**Comment by blaufish** [comment]
The Anthony R Fletcher / Christoph Biedl socat version is from the official ubuntu clevis8 package, so I presume it is well tested on Ubuntu, it is what you get when you perform sudo apt install clevis.
 
My PR I have tested on Ubuntu18. Not at all hardcore unix guru though, so you might consider looking at it carefully. My reasoning is that a nc command line could be determined that is moderately universal (i.e. works with both nmap nc and BSD nc), so it doesn't matter which nc the distro package.

**Comment by blaufish** [comment]
@npmccallum what do you think about detecting socat/nc at runtime too? i.e. detect socat presence using `which socat` and use socat if available, otherwise nc (and presume nc is the nc flavour supported.)

**Comment by michaelbarkdoll** [comment]
Since this is a bash script I believe it would be acceptable to have to pulled in at runtime using hash.  I've created a pull request.  @npmccallum if this needs a custom configure script where is the source code for that so that I can create a pull request to fix it on that end.  Thanks for your time!

**Comment by redg3ar** [comment]
There are 3 flavors of netcat, and each is installed differently per distribution. In Arch Linux, nmap netcat is stripped out to prevent it from conflicting with gnu-netcat. In my personal opinion, the fact that there are 3 flavors makes netcat unsuitable for this project.

**Comment by dkopecek** [comment]
> @npmccallum what do you think about detecting socat/nc at runtime too? i.e. detect socat presence using `which socat` and use socat if available, otherwise nc (and presume nc is the nc flavour supported.)

I would say it is simpler to detect at build-time only. Having auto-detection code in runtime only complicates the code.

**Pull request closed without merging**
