### PR TITLE
Reuse system TPM2TOOLS_TCTI envvar if it is set

### LINKED ISSUE #244: Add a way to configure TPM device path in clevis-{encrypt,decrypt}-tpm2
I am trying to use clevis in my unit tests. As not all PCs have a dedicated TPM2 I am trying to use a software emulator called `swtpm`. I can setup a temporary emulated TPM device with connection over chardev ot TCP.

I would like to configure clevis to use this temp TPM device for testing. This is done with `TPM2TOOLS_TCTI` envvar. I see that clevis-{encrypt,decrypt}-tpm2 scans for `/dev/tpm*` and then constructs `TPM2TOOLS_TCTI` and there is no way for a user to set its own value.

It would be great to have a way for a user to specify its own TPM connection for clevis tools. It is something that would be useful for testing at least.

### PR DESCRIPTION
**Pull request by anatol**
This is a way to customize TPM used for clevis binding/unbinding.
For example for tests against a TPM software emulator:

  TPM2TOOLS_TCTI=swtpm clevis encrypt tpm2 '{}' <<< 'hello, world'

Closes #244

### CODE REVIEW

**Comment by sergio-correia** [comment]
This seems interesting. Could you also provide instructions on how to start `swtpm` and perhaps also add a simple test using it?

**Comment by anatol** [comment]
Here are the instructions I used locally:

First run the command at a machine without any TPM:

```
$ clevis encrypt tpm2 '{}' <<< 'hello, world'
A TPM2 device with the in-kernel resource manager is needed!
```
```
$ TPM2TOOLS_TCTI=swtpm clevis encrypt tpm2 '{}' <<< 'hello, world'
WARNING:tcti:src/util/io.c:252:socket_connect() Failed to connect to host 127.0.0.1, port 2321: errno 111: Connection refused 
ERROR:tcti:src/tss2-tcti/tcti-swtpm.c:592:Tss2_Tcti_Swtpm_Init() Cannot connect to swtpm TPM socket 
WARNING:tcti:src/tss2-tcti/tctildr.c:79:tcti_from_init() TCTI init for function 0x7f22032c9580 failed with a000a 
WARNING:tcti:src/tss2-tcti/tctildr.c:109:tcti_from_info() Could not initialize TCTI named: tcti-swtpm 
ERROR:tcti:src/tss2-tcti/tctildr-dl.c:154:tcti_from_file() Could not initialize TCTI file: swtpm 
ERROR:tcti:src/tss2-tcti/tctildr.c:416:Tss2_TctiLdr_Initialize_Ex() Failed to instantiate TCTI 
ERROR: Could not load tcti, got: "swtpm"
Creating TPM2 primary key failed!
```

Then initialize `swtpm` state:
```
$ swtpm_setup --tpm-state . --tpm2 --ecc --display --create-ek-cert --create-platform-cert --lock-nvram
Starting vTPM manufacturing as anatol:anatol @ Mon 14 Dec 2020 12:09:49 PM PST
TPM is listening on Unix socket.
Successfully created RSA 2048 EK with handle 0x81010001.
  Invoking /usr/share/swtpm/swtpm-localca --type ek --ek b4a78d820000383a835d78533f4eb9dc54750856e5504bc0f51d1a9591f326742b0909f12f9a0792cb2f2125f0d82978cf73d886130e15e1a7082db7e0da04141e10dcf0da10acebb0dd52769f94e8c9186da8d8c0bcd98ed677186be0838a85fbe520d7c21062e14dc45b3ac56822bcb7ad716437dc63d6db729195ccb340fe12c2150ce76d0a26961bb6fecfebbe37202c1b5f3c25e5e5a27e12898e394f377d7c3ba4314bcb6088b98e9d1de3f05c96b472fd9c999dec0a4b1bfe693fbebf4508e69ab3844537e13fc6738443439befe0176fd0180d02a70cded48806d09fa719acea995a41e7b8f43ce40d0af0fc9398762e9754b57011f397091b8dfd19 --dir . --tpm-spec-family 2.0 --tpm-spec-level 0 --tpm-spec-revision 150 --tpm-manufacturer id:00001014 --tpm-model swtpm --tpm-version id:20170619 --tpm2 --configfile /home/anatol/.config/swtpm-localca.conf --optsfile /home/anatol/.config/swtpm-localca.options
swtpm-localca: Successfully created EK certificate locally.
  Invoking /usr/share/swtpm/swtpm-localca --type platform --ek b4a78d820000383a835d78533f4eb9dc54750856e5504bc0f51d1a9591f326742b0909f12f9a0792cb2f2125f0d82978cf73d886130e15e1a7082db7e0da04141e10dcf0da10acebb0dd52769f94e8c9186da8d8c0bcd98ed677186be0838a85fbe520d7c21062e14dc45b3ac56822bcb7ad716437dc63d6db729195ccb340fe12c2150ce76d0a26961bb6fecfebbe37202c1b5f3c25e5e5a27e12898e394f377d7c3ba4314bcb6088b98e9d1de3f05c96b472fd9c999dec0a4b1bfe693fbebf4508e69ab3844537e13fc6738443439befe0176fd0180d02a70cded48806d09fa719acea995a41e7b8f43ce40d0af0fc9398762e9754b57011f397091b8dfd19 --dir . --tpm-spec-family 2.0 --tpm-spec-level 0 --tpm-spec-revision 150 --tpm-manufacturer id:00001014 --tpm-model swtpm --tpm-version id:20170619 --tpm2 --configfile /home/anatol/.config/swtpm-localca.conf --optsfile /home/anatol/.config/swtpm-localca.options
swtpm-localca: Successfully created platform certificate locally.
Successfully created NVRAM area 0x1c00002 for RSA 2048 EK certificate.
Successfully created NVRAM area 0x1c08000 for platform certificate.
Successfully created ECC EK with handle 0x81010016.
  Invoking /usr/share/swtpm/swtpm-localca --type ek --ek x=c1bd8922d9d2a1205145daaec5b3d69aa86895889b6efb09f276b8c8e032c0b323dfdb24ef34fc57d191b0a7df6d6d50,y=5843e851e2be5b5287d94aa1c75edc37e94ec7fe42dd12b352db239b519b224542657888d7989ffdc683489c2a53e25e,id=secp384r1 --dir . --tpm-spec-family 2.0 --tpm-spec-level 0 --tpm-spec-revision 150 --tpm-manufacturer id:00001014 --tpm-model swtpm --tpm-version id:20170619 --tpm2 --configfile /home/anatol/.config/swtpm-localca.conf --optsfile /home/anatol/.config/swtpm-localca.options
swtpm-localca: Successfully created EK certificate locally.
Successfully created NVRAM area 0x1c00016 for ECC EK certificate.
Successfully activated PCR banks sha256,sha1 among sha1,sha256,sha384,sha512.
Successfully authored TPM state.
Ending vTPM manufacturing @ Mon 14 Dec 2020 12:09:49 PM PST
```

Here is the TPM state file:
```
$ ls
tpm2-00.permall
```

Now run the emulator itself:
```
$ swtpm socket --tpmstate dir=. --tpm2 --server type=tcp,port=2321 --ctrl type=tcp,port=2322 --flags not-need-init,startup-clear
```

And the test works:
```
$ TPM2TOOLS_TCTI=swtpm clevis encrypt tpm2 '{}' <<< 'hello, world'
eyJhbGciOiJkaXIiLCJjbGV2aXMiOnsicGluIjoidHBtMiIsInRwbTIiOnsiaGFzaCI6InNoYTI1NiIsImp3a19wcml2IjoiQU80QUlEbm9UbGtIb1dxOWlUeWNqUlAyTVhRekxRdnE4SC13RFJnN3JjRU1TaGpHQUJES3Q4b0syc2hGRDhjYUx2MXMySFpRYVlNVUNNQXU0SGFsaEpvLTNCMU9aWDNDU1BfeGs1UHN2Y2FzamgxLThhX1VvelBFdUR6QlNKQml2bW8xNUkwckFGYXRaNVJscmhRTzJkanNmWnF6OXc5WWpWTHRBWHlJLUVmV0FRQlFVYmQxOEwzSVdjRzJsdnBEc016bU4zbE5JRWFFd3ktdjJHajNhSU9oUWhJR3AwQjNUWjEwZ2dKNlFRQjRRZlhrMkp6T1BJcnpfZDV0MFoxNmk3dkJXa09jSWdfamlhc01lY0FnRkcxcFlRbGZwdDh2NkRhUmlURWRJS3BOR3dFdGItQzZaR19RRGNlaXlNeGIiLCJqd2tfcHViIjoiQUM0QUNBQUxBQUFFMGdBQUFCQUFJTEV6UWszVzFRbjJYVTMtUG9YZTRndGkxeVQyOG53V3YwUjhGSU5jaFZfSCIsImtleSI6ImVjYyJ9fSwiZW5jIjoiQTI1NkdDTSJ9..HaPHzHjgbcDJCpsC.AnK7vlqWyxM2kHNB2g.dLQz-NGUhFoLvs9BtJzC3g
```

**Comment by sergio-correia** [comment]
Thanks for the detailed instructions. I took a quick look sometime last year and encryption worked, like in your example, but decryption did not. Is this expected?

**Comment by anatol** [comment]
What problem do you see? Is it `out of memory for object contexts` like this one?

```
$ TPM2TOOLS_TCTI=swtpm clevis decrypt <<< 'eyJhbGciOiJkaXIiLCJjbGV2aXMiOnsicGluIjoidHBtMiIsInRwbTIiOnsiaGFzaCI6InNoYTI1NiIsImp3a19wcml2IjoiQU80QUlGZmY1QmthZFZVZkVicHRpSXdQTUFvS0lqVWRhQ3AtMWZSSm02VFpzQzNrQUJCRTh0Q0M4U0xiM29HZnVieGk1QlJWUkFBZGs5UkpTaFRBMUhsa2phYlBQdjJlZEZaTXlQQTFNTzA5TmtYVWlEREdaNmdzRmZ5MS1pQ3lFNWo3NnJnTEZUVlZDZk1yLUhYcFNQUGZOdFJJaEo3eXZaREJYdjBmc09MSFpRbVVGOUpMWmVlY080YV9TdGRtdURuZlVHUGZBcTN3dGlpSUV4MmJmSUZnV2xrMGVqRm5kYVFvcTAwVUhYY0hENktmNU9ESU5qenlzbFVxMDg5alhlYVhKeXZGSTE4bTZmZzUxeTNzWFp3VTh4enFYUTVBOFFfLUNqaGxiRXE3OW9ETG1yUVJyZEs1cTlwcmF6ZkMiLCJqd2tfcHViIjoiQUM0QUNBQUxBQUFFMGdBQUFCQUFJTzZaQjdKSDFYclNfYTh2ckZXcEN3V3RzTTJWSFJwMlpwcnZWSjFpMDdXdiIsImtleSI6ImVjYyJ9fSwiZW5jIjoiQTI1NkdDTSJ9..JqvwsY6T4YtEIgiJ.OCEdNA-Jp1Mk7U1dNA.Nu9XnPZgZDYdKVp88AQ5Zg'
WARNING:esys:src/tss2-esys/api/Esys_CreatePrimary.c:393:Esys_CreatePrimary_Finish() Received TPM Error 
ERROR:esys:src/tss2-esys/api/Esys_CreatePrimary.c:135:Esys_CreatePrimary() Esys Finish ErrorCode (0x00000902) 
ERROR: Esys_CreatePrimary(0x902) - tpm:warn(2.0): out of memory for object contexts
ERROR: Unable to run tpm2_createprimary
Creating TPM2 primary key failed!
```

It is because swtpm's interface does not provide TPM resource manager. So a user needs to use something like https://github.com/tpm2-software/tpm2-abrmd that performs TPM context cleanup as soon as the context becomes unneeded.

Another option is to flash contexts manually with `tpm2_flushcontext -t`. For a testing purpose I added `tpm2_flushcontext -t` to `clevis-encrypt-tpm2` and `clevis-decrypt-tpm2` after *every* `tpm2_*` command. And things work fine:

```
$ TPM2TOOLS_TCTI=swtpm clevis encrypt tpm2 '{}' <<< 'hello, world'
eyJhbGciOiJkaXIiLCJjbGV2aXMiOnsicGluIjoidHBtMiIsInRwbTIiOnsiaGFzaCI6InNoYTI1NiIsImp3a19wcml2IjoiQU80QUlJUm5iUGE5V3lsUzV5dWxzMTNtXzBKdkFoUVlzUm9wd1ZkZlF3dk5tS3NsQUJDR3ctekREM25qQ2p3cXFFMC1UaFBqcGNxNzRDTVc1NGs3UFFMaElZRjRjZGxWSEFxZllyZklBQ2lMdExmSkxRZmc2M1pXbkUzQjNLN2Y1RDZHcGZtdEUzVGd5OVdlVlFiSy1qMndKTnlpQ3pXM3c5M0p0c2QtajdySlpMdHQwazVrblBoTXB6Rk5WcDN4NG4tY1gtTGw0ZEcxOEtoYWpYcnVsdEM5c3c2THdveW9aOVlnYkZrZXFVZWdLVGpudS1LdG9FTERmRjdYVTFIQkUwaGJZZDh3bkQxMWhpVWVTX0QxdDBjUHRNQnV1dEFRNnU3MFBFdTVOekFGZjQ5aHFaY3prYWpkbW5SQU5xSnMiLCJqd2tfcHViIjoiQUM0QUNBQUxBQUFFMGdBQUFCQUFJSnR6Ty1hdnl4RjBZWTg0WjlCVkdEbHVfdHVpWnk0aVBNZHlEanFUZTZrZCIsImtleSI6ImVjYyJ9fSwiZW5jIjoiQTI1NkdDTSJ9..DOmYcwpm-WvF57Xq.5fMDFk69MNJzbURzLg._2-6zBgPFimJwaWovKWIgA
$ TPM2TOOLS_TCTI=swtpm clevis decrypt <<< 'eyJhbGciOiJkaXIiLCJjbGV2aXMiOnsicGluIjoidHBtMiIsInRwbTIiOnsiaGFzaCI6InNoYTI1NiIsImp3a19wcml2IjoiQU80QUlJUm5iUGE5V3lsUzV5dWxzMTNtXzBKdkFoUVlzUm9wd1ZkZlF3dk5tS3NsQUJDR3ctekREM25qQ2p3cXFFMC1UaFBqcGNxNzRDTVc1NGs3UFFMaElZRjRjZGxWSEFxZllyZklBQ2lMdExmSkxRZmc2M1pXbkUzQjNLN2Y1RDZHcGZtdEUzVGd5OVdlVlFiSy1qMndKTnlpQ3pXM3c5M0p0c2QtajdySlpMdHQwazVrblBoTXB6Rk5WcDN4NG4tY1gtTGw0ZEcxOEtoYWpYcnVsdEM5c3c2THdveW9aOVlnYkZrZXFVZWdLVGpudS1LdG9FTERmRjdYVTFIQkUwaGJZZDh3bkQxMWhpVWVTX0QxdDBjUHRNQnV1dEFRNnU3MFBFdTVOekFGZjQ5aHFaY3prYWpkbW5SQU5xSnMiLCJqd2tfcHViIjoiQUM0QUNBQUxBQUFFMGdBQUFCQUFJSnR6Ty1hdnl4RjBZWTg0WjlCVkdEbHVfdHVpWnk0aVBNZHlEanFUZTZrZCIsImtleSI6ImVjYyJ9fSwiZW5jIjoiQTI1NkdDTSJ9..DOmYcwpm-WvF57Xq.5fMDFk69MNJzbURzLg._2-6zBgPFimJwaWovKWIgA'
hello, world
```

**Comment by anatol** [comment]
And to add to my previous comment about "out-of-memory" error. It happens because of combination of following reasons:

1. complexity of the TPM API that for some reason allows to have only tiny amount of contexts
2. TPM spec specifies optional API layer called "resource manager" that makes the API usable.  Users who utilize `/dev/tpmrmX` file use a manager implemented as a kernel module.
3. swtpm does not implement the resource manager. Its developer suggests to use some other manager implementation. But it seems existing managers require root permissions to setup and thus making its use in unit tests much more difficult.

I end up modifying my scripts and called `tpm2_flushcontext -t` like here https://github.com/anatol/clevis.go/blob/7fbe18d9406f26ea20e2b88449af4dae8ff14594/tpm2_test_clevis_decrypt#L133

Though I would much prefer that `swtpm` behave like `/dev/tpmrmX` file (i.e. provided a resource manager).

[1] https://groups.google.com/g/swtpm-user/c/h0mg3RwE3mM

**Comment by anatol** [comment]
I added a change that helps to manage active contexts manually. In this case we do not rely on existing tpm2 resource manager.

**Comment by sergio-correia** [comment]
Thanks, it's looking good. You probably need to adapt the checks in the beginning of both `clevis-{encrypt|decrypt}-tpm2` where it tries to use `clevis-pin-tpm2`, if available.

**Comment by anatol** [comment]
@sergio-correia thanks for the reply. Though it is not clear for me what do you mean by

> You probably need to adapt the checks in the beginning of both clevis-{encrypt|decrypt}-tpm2 where it tries to use clevis-pin-tpm2, if available.

**Comment by sergio-correia** [comment]
> @sergio-correia thanks for the reply. Though it is not clear for me what do you mean by
> 
> > You probably need to adapt the checks in the beginning of both clevis-{encrypt|decrypt}-tpm2 where it tries to use clevis-pin-tpm2, if available.

In the beginning of those files (`clevis-encrypt-tpm2` and `clevis-decrypt-tpm2`), you will see it checks whether `clevis-pin-tpm2` is available, and if so, it will use it instead of `clevis-{encrypt|decrypt}-tpm2` -- e.g.: https://github.com/latchset/clevis/blob/master/src/pins/tpm2/clevis-decrypt-tpm2#L21.

`clevis-pin-tpm2` comes from https://github.com/fedora-iot/clevis-pin-tpm2, and may be available -- it usually is in recent Fedora, at least. If that's the case, i.e. if `clevis-pin-tpm2` is present, it won't matter if we set `TPM2TOOLS_TCTI` to `swtpm`, since it will use `clevis-pin-tpm2`, which (at the moment) doesn't care about it. My comment was like: maybe we should make sure to not use `clevis-decrypt-tpm2` if `TPM2TOOLS_TCTI` is set.

**Review by sarroutbi — COMMENTED** [review]
Changes look good to me.

shellcheck tool does not report issues on the patch, and tests run appropriately after patch application:

Ok:                 45  
Expected Fail:      0   
Fail:               0   
Unexpected Pass:    0   
Skipped:            0   
Timeout:            0

**Review by sarroutbi — APPROVED** [review]

**Pull request merged**
