### PR TITLE
Search for tang in arbitrary dir used by Ubuntu 18.04 package

### LINKED ISSUE #143: Clevis doesn't find tang on Ubuntu 18.04
The path is set to `libexecdir`, which is `/usr/libexec`, but [on Ubuntu these files are installed under `/usr/lib/x86_64-linux-gnu`](https://packages.ubuntu.com/bionic/amd64/tang/filelist).

Workaround:

```
sudo ln -s /usr/lib/x86_64-linux-gnu/tangd /usr/libexec/
sudo ln -s /usr/lib/x86_64-linux-gnu/tangd-keygen /usr/libexec/
sudo ln -s /usr/lib/x86_64-linux-gnu/tangd-update /usr/libexec/
```

### PR DESCRIPTION
**Pull request by bviktor**
Fixes #143

### CODE REVIEW

**Comment by sergio-correia** [comment]
Interesting. It finds it here for me without this patch:
```
cat /etc/os-release
NAME="Ubuntu"
VERSION="18.04.5 LTS (Bionic Beaver)"
```
```
[...]
Program /usr/local/libexec/tangd-keygen found: NO
Program /usr/local/lib/x86_64-linux-gnu/tangd-keygen found: NO
Program /usr/local/libexec/tangd-keygen found: NO
Program /usr/lib/x86_64-linux-gnu/tangd-keygen found: YES (/usr/lib/x86_64-linux-gnu/tangd-keygen)
Program /usr/local/libexec/tangd-update found: NO
Program /usr/local/lib/x86_64-linux-gnu/tangd-update found: NO
Program /usr/local/libexec/tangd-update found: NO
Program /usr/lib/x86_64-linux-gnu/tangd-update found: YES (/usr/lib/x86_64-linux-gnu/tangd-update)
Program /usr/local/libexec/tangd found: NO
Program /usr/local/lib/x86_64-linux-gnu/tangd found: NO
Program /usr/local/libexec/tangd found: NO
Program /usr/lib/x86_64-linux-gnu/tangd found: YES (/usr/lib/x86_64-linux-gnu/tangd)
[...]
```

**Comment by bviktor** [comment]
Weird. Where do those `/usr/local` paths come from? I don't have anything like that during build.

**Comment by sergio-correia** [comment]
Probably because I did not specify `--prefix` for meson. If I specify `--prefix=/usr`, I get this instead:
```
Program /usr/libexec/tangd-keygen found: NO
Program /usr/lib/x86_64-linux-gnu/tangd-keygen found: YES (/usr/lib/x86_64-linux-gnu/tangd-keygen)
Program /usr/libexec/tangd-update found: NO
Program /usr/lib/x86_64-linux-gnu/tangd-update found: YES (/usr/lib/x86_64-linux-gnu/tangd-update)
Program /usr/libexec/tangd found: NO
Program /usr/lib/x86_64-linux-gnu/tangd found: YES (/usr/lib/x86_64-linux-gnu/tangd)
```

**Comment by bviktor** [comment]
Ah. I specify `--libdir` during build for some old reason I can't remember ATM. Without that it finds tang indeed. I'll try the TPM and Tang pins with this setup and get back to you ASAP :)

**Comment by bviktor** [comment]
Now I know. Without `--libdir=/usr/lib` TPM unlock never happens during boot. I think it has something to do with the fact that libtss2 libs are under `/usr/lib` in the initramfs, while all other libs are under `/usr/lib/x86_64-linux-gnu`. Will try to build tss2 differently, maybe that'll make a difference, tho I'm fairly certain I already tried that in the past and it caused issues. Maybe it'll behave differently now. Will see.

**Comment by sergio-correia** [comment]
In that case, maybe it would be better to tweak how we look for tpm2, instead (e.g. in `initramfs-tools/hooks`)?

**Comment by bviktor** [comment]
Nah I think it's all good now. I rebuilt tss2 with `--libdir=/usr/lib/x86_64-linux-gnu`, rebuilt Clevis **without** the previously used `--libdir=/usr/lib` flag, and now the tss2 libs are also in the same dir as the other libs in the initramfs, and Clevis unlocks just fine with the TPM2 pin :)

**Pull request closed without merging**
